### ISSUE TITLE
Issues with crumb not appearing

### ISSUE THREAD

**Issue by KrunchMuffin** [prymitive/bootstrap-breadcrumbs#57] opened 2018-11-16 21:25 UTC
Full disclosure, I am a django/python newbie.

this is what I have

**templates/base/base.html**

    ...
    
    <main class="main">

        
        {% include 'base/breadcrumb.html' %}

        
        <div class="container-fluid">
            <div class="animated fadeIn">
                {% block content %}
                {% endblock %}
            </div>

        </div>
        
    </main>

    ...

**templates/base/breadcrumb.html**
The initial "Dashboard" works.

    {% load static %}
    {% load django_bootstrap_breadcrumbs %}

    {% block breadcrumbs %}
        {% breadcrumb "Dashboard" "/dashboard" %}
    {% endblock %}

    {% block breadcrumb %}
        {% render_breadcrumbs %}
    {% endblock %}

**templates/accounts/index.html**

```
{% extends 'base/base.html' %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Account List" "account-list" %}
{% endblock %}
{% load common_extras %}
{% block content %}
```

All I end up with is `Dashboard`. I have tried different configurations. There are no errors. 
Django 2.1.2 Python 3.7

**Comment by prymitive** [comment] 2018-11-16 21:47
It's been a while since I wrote any django code but I'm sure we can crack it together.
I *think* it's because `{% render_breadcrumbs %}` is called to early. I would try moving it out of `templates/base/breadcrumb.html` and into `templates/base/base.html` or maybe even `templates/accounts/index.html` to see if that helps.
That's the only quick tip I have right now, let me know if that still doesn't work.

**Comment by KrunchMuffin** [comment] 2018-11-16 21:55
Hey! Thanks for the quick reply!

I tried it in different places with same result. So confused.

**Comment by prymitive** [comment] 2018-11-16 21:57
🤔
I'll look into this over weekend, should be easy to reproduce

**Comment by KrunchMuffin** [comment] 2018-11-16 21:57
Thanks. I'll keep pluggin' away.

**Comment by KrunchMuffin** [comment] 2018-11-16 22:03
I think I got it! I took all the breadcrumb.html code and replaced the include inside base.html with it and it worked. So I guess there is an issue with includes?

**Comment by KrunchMuffin** [comment] 2018-11-16 22:08
I have a question while I have you. In paths where I have an ID ie. 159, would it be possible to replace that with the actual company name it represents and use it in the breadcrumb? So...

`Dashboard / Accounts / ACME Inc. / Detail`

**Comment by prymitive** [comment] 2018-11-16 22:08
I think that if you only got `Dashboard` than it's an ordering issue (rendering breadcrumbs list before it was fully populated), so it might be related to the way inheritance chain is setup.

**Comment by prymitive** [comment] 2018-11-16 22:14
> I have a question while I have you. In paths where I have an ID ie. 159, would it be possible to replace that with the actual company name it represents and use it in the breadcrumb? So...
> 
> `Dashboard / Accounts / ACME Inc. / Detail`

If you are using Django models than you can define [__str__()](https://docs.djangoproject.com/en/1.11/ref/models/instances/#str) and pass model instance as `$label` argument ([docs](https://django-bootstrap-breadcrumbs.readthedocs.io/en/latest/#breadcrumb)) or pass any model attribute there as `$label`

**Comment by KrunchMuffin** [comment] 2018-11-16 22:20
Ok, cool. thanks again.

**Comment by KrunchMuffin** [comment] 2018-12-09 06:33
Hey again.

Having a small issue I can't figure out.

I get this far

![image](https://user-images.githubusercontent.com/1037197/49694063-bd7f6b80-fb50-11e8-9534-5e69cf6f6ea1.png)

But when I select a user to view detail on, I lose the company name

![image](https://user-images.githubusercontent.com/1037197/49694068-cec87800-fb50-11e8-8e66-f5cf9bdb2d00.png)

Goes like this...

Dashboard: (base.html) 
`{% breadcrumb "Dashboard" "/dashboard" %}`

Account List: (index.html) 
`{% extends 'base/base.html' %}`
`{% breadcrumb "Account List" "accountmgmt:account-list" %}` 

Martin's Cafe: (detail.html) 
`{% extends 'accounts/index.html' %}`
`{% breadcrumb detail.company_name|title "accountmgmt:account-detail" detail.profile_id %}` 

User List: (userlist.html)
`{% extends 'accounts/index.html' %}`
`{% breadcrumb company_name|title "accountmgmt:account-detail" pid %}`
`{% breadcrumb "User List" "accountmgmt:user-list" pid %}`

Big Boss: (userdetail.html) 
`{% extends 'accounts/userlist.html' %}`
`{% breadcrumb detail.fullname|title "accountmgmt:user-detail" detail.user_id %}`

**Comment by KrunchMuffin** [comment] 2018-12-10 19:40
hmmm...not likely. it would have company and profile but not user

**Comment by prymitive** [comment] 2018-12-10 20:48
Doesn't this mean that `detail` object used when you render those breadcrumbs can't render all of those, since for some breadcrumbs it needs to be a user but for others it's a company?
I mean - when you render user page `detail` object is an user object, so when partial for rendering company title gets that passed it can't find `company_name` on it.
I would recommend using more meaningful object names so it's obvious what you need to pass.

**Closed as completed** 2018-12-12 06:25 UTC
